# Generated by Django 4.1.12 on 2023-11-06 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaint_images/')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'complaint_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_description', models.TextField()),
                ('room_no', models.TextField()),
                ('hostel_name', models.TextField()),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('not_verified', 'Not Verified')], default='pending', max_length=20)),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('not_resolved', 'Not Resolved')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
