# Generated by Django 4.1.12 on 2023-11-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_complaint_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complaint_image',
        ),
    ]
